"""
config.py — shared configuration for all Member 3 models.
Edit this file to change dataset paths, hyperparameters, or training settings.

Dataset facts (from Member 1's preprocessing — data_quality_and_processing_summary.csv):
  - 4,192 original daily records across 40 SCATS sites, 139 location/direction entries
  - 402,432 time-series records total (after melt + duplicate resolution)
  - 2,976 duplicate site-location-timestamp records resolved by averaging
  - No missing, invalid or negative values found
  - Normalisation: min=0.0, max=636.0 (training set only; val/test may exceed 1.0)
  - Chronological split: train Oct 01-21 (278,016 rows), val Oct 22-26 (61,536), test Oct 27-31 (62,880)
  - Window size 12 → train sequences: 276,348 | val: 59,880 | test: 61,248
"""

import os

# ── Paths ──────────────────────────────────────────────────────────────────────
BASE_DIR   = os.path.dirname(os.path.abspath(__file__))
DATA_DIR   = os.path.join(BASE_DIR, "data")
OUTPUT_DIR = os.path.join(BASE_DIR, "outputs")
MODEL_DIR  = os.path.join(OUTPUT_DIR, "checkpoints")
PLOT_DIR   = os.path.join(OUTPUT_DIR, "plots")

for d in [OUTPUT_DIR, MODEL_DIR, PLOT_DIR]:
    os.makedirs(d, exist_ok=True)

# ── Dataset (Member 1's files) ─────────────────────────────────────────────────
# Primary: raw XLS — loader will call Member 1's pipeline to produce processed files.
RAW_XLS          = os.path.join(DATA_DIR, "Scats_Data_October_2006.xls")
# Secondary: pre-processed NPZ (generated by data_preprocessing.py).
# If this exists, loader uses it directly and skips re-processing.
NPZ_PATH         = os.path.join(DATA_DIR, "model_ready_sequences_window12.npz")

# Which SCATS site(s) to train on. None = use all (recommended for full training).
TARGET_SITES     = None

# ── Sequence / split settings (must match Member 1's pipeline) ─────────────
SEQ_LEN          = 12      # 12 × 15-min intervals = 3 hours of history
PRED_LEN         = 1       # predict the next 15-min volume

# Member 1's actual chronological split (days 1-21 / 22-26 / 27-31 of October 2006)
TRAIN_DAYS_END   = 21
VAL_DAYS_END     = 26

# Scaling constants fitted on training data by Member 1 (do NOT refit on full data)
TRAIN_FLOW_MIN   = 0.0
TRAIN_FLOW_MAX   = 636.0

# ── Training ───────────────────────────────────────────────────────────────────
BATCH_SIZE       = 512     # larger batch = faster training on CPU
EPOCHS           = 20
LEARNING_RATE    = 1e-3
PATIENCE         = 10      # early-stopping patience (epochs)
SEED             = 42

# ── Model shared ──────────────────────────────────────────────────────────────
INPUT_SIZE       = 1       # univariate: scaled traffic volume
HIDDEN_SIZE      = 64
NUM_LAYERS       = 2
DROPOUT          = 0.2

# ── Transformer-specific ──────────────────────────────────────────────────────
NHEAD            = 4       # attention heads (must divide HIDDEN_SIZE evenly)
DIM_FEEDFORWARD  = 128

# ── Evaluation ────────────────────────────────────────────────────────────────
METRICS = ["MAE", "RMSE", "MAPE"]
